import type { FormConfig } from '../shared/types';

const UEQ_ITEMS = [
  { negative: 'Obstructivo', positive: 'Impulsor de apoyo' },
  { negative: 'Complicado', positive: 'Fácil' },
  { negative: 'Ineficiente', positive: 'Eficiente' },
  { negative: 'Confuso', positive: 'Claro' },
  { negative: 'Aburrido', positive: 'Emocionante' },
  { negative: 'No interesante', positive: 'Interesante' },
  { negative: 'Convencional', positive: 'Original' },
  { negative: 'Convencional', positive: 'Novedoso' },
];

export const POSTTEST_CONFIG: FormConfig = {
  formId: 'posttest',
  formLabel: 'Post-Test',
  closedItemCount: 52,
  openItemCount: 5,
  intro: {
    title: 'Post-Test · Prueba con Usuarios',
    text: 'Gracias por usar la aplicación. Este formulario recoge tu experiencia y toma unos 10 minutos. Ingresa la contraseña de cierre que recibiste al terminar la fase 2.',
    requiresPassword: true,
  },
  complete: {
    title: '¡Gracias por participar!',
    subtitle: 'Tus respuestas son muy valiosas para mejorar la aplicación.',
  },
  sections: [
    {
      id: 'sus',
      name: 'SUS',
      transition: {
        title: 'Sobre la usabilidad',
        icon: '🖥️',
        hint: 'Indica tu nivel de acuerdo con cada afirmación sobre la aplicación.',
      },
      items: [
        { type: 'likert', key: 'sus_1', instrument: 'SUS', text: 'Me parece que me gustaría usar esta aplicación con frecuencia.' },
        { type: 'likert', key: 'sus_2', instrument: 'SUS', text: 'Encontré la aplicación innecesariamente compleja.' },
        { type: 'likert', key: 'sus_3', instrument: 'SUS', text: 'Pensé que la aplicación era fácil de usar.' },
        { type: 'likert', key: 'sus_4', instrument: 'SUS', text: 'Creo que necesitaría el apoyo de un experto para poder usar esta aplicación.' },
        { type: 'likert', key: 'sus_5', instrument: 'SUS', text: 'Encontré que las distintas funciones de la aplicación estaban bien integradas.' },
        { type: 'likert', key: 'sus_6', instrument: 'SUS', text: 'Pensé que había demasiadas inconsistencias en la aplicación.' },
        { type: 'likert', key: 'sus_7', instrument: 'SUS', text: 'Creo que la mayoría de las personas aprenderían a usar esta aplicación muy rápidamente.' },
        { type: 'likert', key: 'sus_8', instrument: 'SUS', text: 'Encontré la aplicación muy incómoda de usar.' },
        { type: 'likert', key: 'sus_9', instrument: 'SUS', text: 'Me sentí muy confiado/a al usar la aplicación.' },
        { type: 'likert', key: 'sus_10', instrument: 'SUS', text: 'Necesité aprender muchas cosas antes de poder usar esta aplicación.' },
      ],
    },
    {
      id: 'ueq',
      name: 'UEQ-S',
      transition: {
        title: 'Sobre tu experiencia general',
        icon: '⭐',
        hint: 'Ahora que la usaste, describe cómo fue tu experiencia real con la aplicación.',
      },
      items: UEQ_ITEMS.map((pair, i) => ({
        type: 'semantic' as const,
        key: `ueq_${i + 1}`,
        negative: pair.negative,
        positive: pair.positive,
      })),
    },
    {
      id: 'tam',
      name: 'TAM',
      transition: {
        title: '¿Qué tan útil resultó ser?',
        icon: '🎯',
        hint: 'Indica qué tan probable te parece cada afirmación según tu experiencia.',
      },
      items: [
        { type: 'likert', key: 'tam_p1', instrument: 'TAM', text: 'Usar esta aplicación me permitió realizar tareas de análisis UX más rápidamente.' },
        { type: 'likert', key: 'tam_p2', instrument: 'TAM', text: 'Usar esta aplicación mejoró mi desempeño en habilidades de diseño UX.' },
        { type: 'likert', key: 'tam_p3', instrument: 'TAM', text: 'Usar esta aplicación aumentó mi productividad como estudiante de UX.' },
        { type: 'likert', key: 'tam_p4', instrument: 'TAM', text: 'Usar esta aplicación potenció mi efectividad al evaluar interfaces.' },
        { type: 'likert', key: 'tam_p5', instrument: 'TAM', text: 'Usar esta aplicación me facilitó el aprendizaje de UX.' },
        { type: 'likert', key: 'tam_p6', instrument: 'TAM', text: 'Encontré esta aplicación útil para mi formación en UX.' },
      ],
    },
    {
      id: 'imi',
      name: 'IMI',
      transition: {
        title: 'Sobre tu motivación',
        icon: '🔥',
        hint: 'Indica qué tan verdadera te resulta cada afirmación sobre tu experiencia.',
      },
      items: [
        { type: 'likert', key: 'imi_1', instrument: 'IMI', text: 'Disfruté mucho hacer esta actividad.' },
        { type: 'likert', key: 'imi_2', instrument: 'IMI', text: 'Esta actividad fue entretenida.' },
        { type: 'likert', key: 'imi_3', instrument: 'IMI', text: 'Describí esta actividad como muy interesante.' },
        { type: 'likert', key: 'imi_4', instrument: 'IMI', text: 'Pensé que esta actividad era bastante disfrutable.' },
        { type: 'likert', key: 'imi_5', instrument: 'IMI', text: 'Mientras hacía esta actividad, pensé en cuánto me estaba gustando.' },
        { type: 'likert', key: 'imi_6', instrument: 'IMI', text: 'Creo que esta actividad es bastante aburrida.', reversed: true },
        { type: 'likert', key: 'imi_7', instrument: 'IMI', text: 'Esta actividad no captó mi atención en absoluto.', reversed: true },
        { type: 'likert', key: 'imi_8', instrument: 'IMI', text: 'Creo que soy bastante bueno/a en esta actividad.' },
        { type: 'likert', key: 'imi_9', instrument: 'IMI', text: 'Me sentí bastante competente al hacer esta actividad.' },
        { type: 'likert', key: 'imi_10', instrument: 'IMI', text: 'Creo que tuve cierta elección sobre cómo hacer esta actividad.' },
        { type: 'likert', key: 'imi_11', instrument: 'IMI', text: 'Sentí que era mi propia decisión hacer esta actividad.' },
        { type: 'likert', key: 'imi_12', instrument: 'IMI', text: 'Hice esta actividad porque quería hacerla.' },
        { type: 'likert', key: 'imi_13', instrument: 'IMI', text: 'Me sentí muy tenso/a mientras hacía esta actividad.' },
        { type: 'likert', key: 'imi_14', instrument: 'IMI', text: 'Me sentí ansioso/a mientras trabajaba en esta actividad.' },
      ],
    },
    {
      id: 'geq',
      name: 'GEQ',
      transition: {
        title: '¿Cómo te sentiste al terminar?',
        icon: '🎮',
        hint: 'Indica cómo te sentiste al terminar de usar la aplicación.',
      },
      items: [
        { type: 'likert', key: 'geq_1', instrument: 'GEQ', text: 'Me sentí revitalizado/a.' },
        { type: 'likert', key: 'geq_2', instrument: 'GEQ', text: 'Me sentí mal.' },
        { type: 'likert', key: 'geq_3', instrument: 'GEQ', text: 'Me costó volver a la realidad.' },
        { type: 'likert', key: 'geq_4', instrument: 'GEQ', text: 'Sentí que fue una victoria.' },
        { type: 'likert', key: 'geq_5', instrument: 'GEQ', text: 'Sentí que fue una pérdida de tiempo.' },
        { type: 'likert', key: 'geq_6', instrument: 'GEQ', text: 'Me sentí con energía.' },
        { type: 'likert', key: 'geq_7', instrument: 'GEQ', text: 'Me sentí satisfecho/a.' },
        { type: 'likert', key: 'geq_8', instrument: 'GEQ', text: 'Me sentí desorientado/a.' },
        { type: 'likert', key: 'geq_9', instrument: 'GEQ', text: 'Me sentí agotado/a.' },
        { type: 'likert', key: 'geq_10', instrument: 'GEQ', text: 'Sentí que podría haber hecho cosas más útiles.' },
        { type: 'likert', key: 'geq_11', instrument: 'GEQ', text: 'Me sentí poderoso/a.' },
        { type: 'likert', key: 'geq_12', instrument: 'GEQ', text: 'Me sentí cansado/a.' },
        { type: 'likert', key: 'geq_13', instrument: 'GEQ', text: 'Sentí arrepentimiento.' },
        { type: 'likert', key: 'geq_14', instrument: 'GEQ', text: 'Tuve la sensación de haber regresado de un viaje.' },
      ],
    },
    {
      id: 'open',
      name: 'Abiertas',
      transition: {
        title: 'Por último, tu opinión',
        icon: '💬',
        hint: 'Estas preguntas son sobre cada módulo de la app. Sé tan específico/a como quieras.',
      },
      items: [
        {
          type: 'open',
          key: 'open_p1',
          module: 'Módulo de Ejercicios',
          text: '¿Los ejercicios de evaluación heurística, diseño UI y pruebas con usuarios te resultaron útiles y comprensibles? ¿Hubo algún tipo de ejercicio que encontraras confuso o que mejorarías?',
        },
        {
          type: 'open',
          key: 'open_p2',
          module: 'Módulo de Perfil',
          text: '¿La información de tu perfil (nivel, puntos, racha) fue fácil de encontrar y entender? ¿Sientes que refleja tu progreso real dentro de la aplicación?',
        },
        {
          type: 'open',
          key: 'open_p3',
          module: 'Módulo de Progreso',
          text: '¿Las estadísticas y sugerencias del módulo de progreso te ayudaron a entender en qué áreas de UX necesitas practicar más? ¿Qué cambiarías o añadirías?',
        },
        {
          type: 'open',
          key: 'open_p4',
          module: 'Módulo de Recompensas',
          text: '¿Las insignias y logros que obtuviste te generaron motivación para seguir practicando? ¿El sistema de recompensas te pareció justo y claro?',
        },
        {
          type: 'open',
          key: 'open_p5',
          module: 'Módulo de Personalización',
          text: '¿Pudiste ajustar la aplicación a tus preferencias con facilidad? ¿Hay alguna opción de personalización que hayas echado de menos o que te haya resultado confusa?',
        },
      ],
    },
  ],
};
